mode: rule
mixed-port: 7897
allow-lan: false
log-level: debug
ipv6: true
secret: ''
external-controller: 127.0.0.1:9097
#find-process-mode: always # always/strict默认/off
geodata-mode: true
geodata-loader: standard # standard/memconservative
geo-auto-update: true # 是否自动更新 geodata
geo-update-interval: 24 # 更新间隔，单位：小时
geox-url:
  mmdb: "https://github.com/Hackl0us/GeoIP2-CN/raw/release/Country.mmdb"
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"

dns:
  enable: true
  listen: :53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    # 如果想改为re-deir模式，取消下一行注释 #
    # - '+.*'
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - 'cable.auth.com'
    - 'network-test.debian.org'
    - 'detectportal.firefox.com'
    - 'resolver1.opendns.com'
    - '*.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - '*.xboxlive.com'
    - 'stun.*'
    - 'global.turn.twilio.com'
    - 'global.stun.twilio.com'
    - 'localhost.*.qq.com'
    - 'localhost.*.weixin.qq.com'
    - '*.logon.battlenet.com.cn'
    - '*.logon.battle.net'
    - '*.blzstatic.cn'
    - 'time.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'time.*.apple.com'
    - 'time-ios.apple.com'
    - 'time1.*.com'
    - 'time2.*.com'
    - 'time3.*.com'
    - 'time4.*.com'
    - 'time5.*.com'
    - 'time6.*.com'
    - 'time7.*.com'
    - 'ntp1.*.com'
    - 'ntp2.*.com'
    - 'ntp.*.com'
    - 'ntp?.*.com'
    - 'time?.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'ntp3.*.com'
    - 'ntp4.*.com'
    - 'ntp5.*.com'
    - 'ntp6.*.com'
    - 'ntp7.*.com'
    - '*.time.edu.cn'
    - '+.pool.ntp.org'
    - 'time1.cloud.tencent.com'
    - 'music.163.com'
    - '*.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - 'y.qq.com'
    - '*.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - 'localhost.ptlogin2.qq.com'
    - 'localhost.sec.qq.com'
    - '+.qq.com'
    - '+.tencent.com'
    - '+.srv.nintendo.net'
    - '*.n.n.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.*.xboxlive.com'
    - 'xbox.*.microsoft.com'
    - 'xnotify.xboxlive.com'
    - '+.battlenet.com.cn'
    - '+.wotgame.cn'
    - '+.wggames.cn'
    - '+.wowsgame.cn'
    - '+.wargaming.net'
    - 'proxy.golang.org'
    - 'stun.*.*'
    - 'stun.*.*.*'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - '+.stun.*.*.*.*'
    - '+.stun.*.*.*.*.*'
    - 'heartbeat.belkin.com'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - '*.router.asus.com'
    - 'mesu.apple.com'
    - 'swscan.apple.com'
    - 'swquery.apple.com'
    - 'swdownload.apple.com'
    - 'swcdn.apple.com'
    - 'swdist.apple.com'
    - 'lens.l.google.com'
    - 'stun.l.google.com'
    - 'na.b.g-tun.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.ff14.sdo.com'
    - 'ff.dorado.sdo.com'
    - '*.mcdn.bilivideo.cn'
    - '+.media.dssott.com'
    - 'shark007.net'
    - 'MijiaCloud'
    - '+.cmbchina.com'
    - '+.cmbimg.com'
    - 'local.adguard.org'
    - 'static.adtidy.org'
    - '+.sandai.net'
    - '+.n0808.com'
    - '+.3gppnetwork.org'
    - '1c.premierzal.ru'
    - '6.pocketnet.app'
    - '6ahddutb1ucc3cp.ru'
    - 'acxx.de'
    - 'aegir.sexy'
    - 'api.alarmasqueretaro.com'
    - 'bt.ktrackers.com'
    - 'bt1.archive.org'
    - 'bt2.archive.org'
    - 'concen.org'
    - 'd40969.acod.regrucolo.ru'
    - 'ec2-18-191-163-220.us-east-2.compute.amazonaws.com'
    - 'epider.me'
    - 'evan.im'
    - 'exodus.desync.com'
    - 'fe.dealclub.de'
    - 'fh2.cmp-gaming.com'
    - 'free.publictracker.xyz'
    - 'hz.is'
    - 'ipv6.fuuuuuck.com'
    - 'jutone.com'
    - 'mail.artixlinux.org'
    - 'martin-gebhardt.eu'
    - 'moonburrow.club'
    - 'movies.zsw.ca'
    - 'new-line.net'
    - 'ns1.monolithindustries.com'
    - 'odd-hd.fr'
    - 'oh.fuuuuuck.com'
    - 'open.demonii.com'
    - 'open.dstud.io'
    - 'open.stealth.si'
    - 'open.tracker.ink'
    - 'open.u-p.pw'
    - 'open.xxtor.com'
    - 'opentor.org'
    - 'opentracker.io'
    - 'p4p.arenabg.com'
    - 'public.tracker.vraphim.com'
    - 'retracker.hotplug.ru'
    - 'retracker.lanta.me'
    - 'retracker01-msk-virt.corbina.net'
    - 'ryjer.com'
    - 'su-data.com'
    - 'tamas3.ynh.fr'
    - 'tk1.trackerservers.com'
    - 'torrents.artixlinux.org'
    - 'tracker-udp.gbitt.info'
    - 'tracker.0x7c0.com'
    - 'tracker.anima.nz'
    - 'tracker.artixlinux.org'
    - 'tracker.birkenwald.de'
    - 'tracker.ccp.ovh'
    - 'tracker.cubonegro.lol'
    - 'tracker.cyberia.is'
    - 'tracker.ddunlimited.net'
    - 'tracker.dler.com'
    - 'tracker.dler.org'
    - 'tracker.edkj.club'
    - 'tracker.filemail.com'
    - 'tracker.fnix.net'
    - 'tracker.mirrorbay.org'
    - 'tracker.moeking.me'
    - 'tracker.opentrackr.org'
    - 'tracker.picotorrent.one'
    - 'tracker.qu.ax'
    - 'tracker.skyts.net'
    - 'tracker.srv00.com'
    - 'tracker.swateam.org.uk'
    - 'tracker.t-rb.org'
    - 'tracker.theoks.net'
    - 'tracker.therarbg.com'
    - 'tracker.therarbg.to'
    - 'tracker.tiny-vps.com'
    - 'tracker.torrent.eu.org'
    - 'tracker.torrust-demo.com'
    - 'tracker.tryhackx.org'
    - 'tracker.vds.nz'
    - 'tracker1.myporn.club'
    - 'tracker2.dler.org'
    - 'tracker2.itzmx.com'
    - 'tracker3.itzmx.com'
    - 'tracker4.itzmx.com'
    - 'ttk2.nbaonlineservice.com'
    - 'u4.trakx.crim.ist'
    - 'u6.trakx.crim.ist'
    - 'uploads.gamecoast.net'
    - 'wepzone.net'
    - 'www.torrent.eu.org'
    - 'y.paranoid.agency'
    - 'adguardteam.github.io'
    - 'anti-ad.net'
    - '*.cmpassport.com'
    - 'id6.me'
    - 'open.e.189.cn'
    - 'mdn.open.wo.cn'
    - 'opencloud.wostore.cn'
    - 'auth.wosms.cn'
    - '*.jegotrip.com.cn'
    - '*.icitymobile.mobi'
    - '*.pingan.com.cn'
    - '*.cmbchina.com'
    - 'pool.ntp.org'
    - '*.pool.ntp.org'
    - '*.ntp.org.cn'
    - 'PDC._msDCS.*.*'
    - 'DC._msDCS.*.*'
    - 'GC._msDCS.*.*'
    - '+.infinitynewtab.com'
    - '+.baidu.com'
    - '+.baidu-int.com'
    - 'timgmb.bdimg.com'
    - 'report.url.cn'
    - 'zyx.qq.com'

  nameserver-policy:
    '+.bmedi.cn': system
    '+.bgmedri.cn': system
    'geosite:cn':
      - 119.29.29.29
      - 180.76.76.76
      - 2400:3200::1
      - 240c::6666
      #- https://223.5.5.5/dns-query
      #- https://1.12.12.12/dns-query
      #- https://223.6.6.6/dns-query
      #- https://120.53.53.53/dns-query
    'geosite:geolocation-!cn':
      - 8.8.8.8
      - 2620:119:35::35
      - 2610:a1:1018::5
      #- 2001:4860:4860::8888
      #- https://doh.apad.pro/dns-query
      #- https://1.0.0.1/dns-query
      #- https://208.67.222.222/dns-query
  nameserver:
    - 119.29.29.29
    - 180.76.76.76
    - 2400:3200::1
    - 240c::6666
    #- system
    #- https://223.5.5.5/dns-query
    #- https://1.12.12.12/dns-query
    #- https://223.6.6.6/dns-query
    #- https://120.53.53.53/dns-query
  fallback:
    - 8.8.8.8
    - 2620:119:35::35
    - 2610:a1:1018::5
    #- https://doh.apad.pro/dns-query
    #- https://1.0.0.1/dns-query
    #- https://208.67.222.222/dns-query
  #proxy-server-nameserver:
    #- https://doh.apad.pro/dns-query
    #- https://1.0.0.1/dns-query
    #- https://208.67.222.222/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    geosite:
      - gfw
    ipcidr:
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.x.com'

tun:
  enable: true
  stack: gvisor # system/gvisor/mixed
  dns-hijack:
    - 198.18.0.2:53 # 当 `fake-ip-range` 是 198.18.0.1/16, 应该劫持 198.18.0.2:53
  auto-route: true # 配置路由表
  auto-detect-interface: true # 自动识别出口网卡
  inet4-route-exclude-address:
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 255.255.255.255/32
    - 239.255.255.250/32
    # icm软件狗扫描报错
    - 211.103.187.181/32
    # - geoip-code: CN
        
hosts:
  'localhost': 127.0.0.1
  # 阻止FinalShell升级
  'www.youtusoft.com': 127.0.0.1
  'youtusoft.com': 127.0.0.1
  'hostbuf.com': 127.0.0.1
  'www.hostbuf.com': 127.0.0.1
  'dkys.org': 127.0.0.1
  'tcpspeed.com': 127.0.0.1
  'www.wn1998.com': 127.0.0.1
  'wn1998.com': 127.0.0.1
  'pwlt.wn1998.com': 127.0.0.1
  'backup.www.hostbuf.com': 127.0.0.1
  #'.google.cn': google.com
  #'.g.cn': google.com

proxies:

proxy-groups:

rule-providers:
  applications:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400
  reject:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  openai:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Repcz/Tool/X/Clash/Rules/OpenAI.list"
    path: ./ruleset/applications.yaml
    interval: 86400
  copilot:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/Repcz/Tool/X/Clash/Rules/Copilot.list"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  # 自定义规则
  - PROCESS-NAME,FinalShell.exe,PROXY
  - PROCESS-NAME,FinalShell,PROXY
  - DOMAIN-KEYWORD,weixin,DIRECT
  - DOMAIN-SUFFIX,garmin.com,PROXY

  # 白名单规则 https://github.com/Loyalsoldier/clash-rules
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,openai,PROXY
  - RULE-SET,copilot,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT,no-resolve
  - RULE-SET,cncidr,DIRECT,no-resolve
  - RULE-SET,telegramcidr,PROXY,no-resolve
  - GEOIP,LAN,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,PROXY